### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by rkristelijn** [webextensions/headless-integration#1]
# Steps to reproduce
`npm test -s`

  Application
    ✓ should be able to read innerText for a given selector (4535ms)
    ✓ should be able to take screenshot for a given selector (4472ms)
    ✓ should load the basic example properly (2540ms)
    ✓ should be able to perform a simple click action (4353ms)
    ✓ should be able to type in an input field (6206ms)
    1) should load the login access page properly

  5 passing (23s)
  1 failing

  1) Application
       should load the login access page properly:
     Error: net::ERR_CONNECTION_REFUSED at http://localhost:3000/
      at navigate (node_modules/puppeteer/lib/FrameManager.js:121:37)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
    -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.goto (node_modules/puppeteer/lib/Page.js:629:49)
      at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at asyncRunTest (src/headless-integration.js:92:38)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
      at async Context.<anonymous> (test/headless-integration.test.js:41:32)

# linked issue
https://github.com/rkristelijn/login/issues/1

# depts check
`node ./node_modules/login-express-session/bin/www` now runs without errors of bootstrap, because of fix https://github.com/rkristelijn/login/commit/309849a60db1a36dde90b4c6b5e5840f496cc4fb

# npm package
The code is now exposed as npm package [login-express-session](https://www.npmjs.com/package/login-express-session) for ease of integration

# Result
Test `should load the login access page properly` still fails. Let me know if I can be of more help

**Comment by webextensions** [comment]
Thanks :-)

Merged into `master`. Marking closed.
